// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggmbmpuekasxydvnclfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbWJtcHVla2FzeHlkdm5jbGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NzQ1MjYsImV4cCI6MjA5NTQ1MDUyNn0.ZL4EXNykgSnWiV9EorYsBKBW_VWDOsD3Ukheiya4ZI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false,
    autoRefreshToken: true,
  }
});